/**
 * Shared French labels for wording that repeats across screens.
 *
 * One-off labels stay next to the component that renders them; this file exists so recurring
 * wording -- navigation, common actions, business statuses -- cannot drift between screens.
 */
export const labels = {
  app: {
    name: "Solution Mécanique",
  },
  nav: {
    work: "Interventions",
    primary: "Navigation principale",
    groupWorkshop: "Atelier",
    groupClients: "Clients",
    groupManagement: "Gestion",
    clients: "Clients",
    vehicles: "Véhicules",
    inventory: "Inventaire",
    settings: "Paramètres",
    profile: "Mon profil",
    signOut: "Déconnexion",
    account: "Mon compte",
    invoiceOptions: "Options de facturation",
    openUserMenu: "Ouvrir le menu utilisateur",
    openSidebar: "Ouvrir la navigation",
    closeSidebar: "Fermer la navigation",
    openOptions: "Ouvrir les options",
    selectTab: "Sélectionner un onglet",
  },
  search: {
    emptyHint: "Ajustez votre recherche ou vos filtres.",
    empty: "Aucun résultat",
    search: "Rechercher",
    // The field is named for what it holds, the button for what it does, so the filter panel does
    // not carry the same word twice.
    keyword: "Recherche",
    pagination: "Pagination",
    previous: "Précédent",
    next: "Suivant",
    showing: "Résultats",
    to: "à",
  },
  actions: {
    edit: "Modifier",
    print: "Imprimer",
    download: "Télécharger",
    delete: "Supprimer",
    save: "Enregistrer",
    cancel: "Annuler",
    apply: "Appliquer",
    add: "Ajouter",
    open: "Ouvrir",
    close: "Fermer",
  },
  /**
   * Business statuses. These stay distinct on purpose: "Non terminées" covers every intervention
   * without an invoice that is not closed, which is broader than "En cours".
   */
  workStatus: {
    all: "Tous",
    unfinished: "Non terminées",
    inProgress: "En cours",
    closed: "Terminées",
    overdue: "En retard",
    /** Toggle between not-yet-invoiced interventions and issued invoices. */
    work: "Interventions",
    completed: "Facturées",
    /** Names the toggle itself: a switch is named for what turning it on does. */
    showInvoices: "Afficher les factures",
  },
  common: {
    notProvided: "Non renseigné",
    save: "Enregistrer",
    cancel: "Annuler",
    description: "Description",
    notes: "Notes",
    status: "Statut",
    summary: "Résumé",
    yes: "Oui",
    no: "Non",
    code: "Code",
    name: "Libellé",
    price: "Prix",
    quantity: "Quantité",
    unit: "Unité",
    discount: "Remise",
    subtotal: "Sous-total",
    tax: "TVA",
    total: "Total",
    noValue: "(vide)",
    codePlaceholder: "code…",
    clientEmail: "E-mail du client",
    sendClientEmail: "Envoyer un e-mail au client",
  },
  dialogs: {
    applyDiscount: "Appliquer une remise",
    percent: "Pourcentage",
    deleteInvoice: "Supprimer une facture",
    issueInvoice: "Terminer l’intervention et émettre une facture",
    dueDays: "Délai de paiement (jours)",
    paymentType: "Mode de paiement",
    issueOffer: "Émettre un devis",
    offerAccepted: "Devis accepté par le client",
    startNewRepairJob: "Démarrer une nouvelle réparation",
    // The document named here differs with the activity, and so does the French article, so the
    // two cases are whole sentences rather than a stem plus a word.
    showVehicleOnInvoice: "Afficher les informations du véhicule sur la facture",
    showVehicleOnEstimate: "Afficher les informations du véhicule sur le devis",
    // The switch above it starts a repair job, not a new intervention.
    newJobNotes: "Notes à ajouter à la nouvelle réparation",
    offerAcceptedHelp: "Créez une nouvelle réparation ou complétez une réparation existante à partir du contenu du devis.",
    repairJobTarget: "Réparation à compléter",
  },
  clients: {
    findClients: "Rechercher un client",
    searchPlaceholder: "nom, adresse ou téléphone…",
    information: "Informations client",
    newClient: "Nouveau client",
    enterDetails: "Saisir les informations",
    editDetails: "Modifier les informations",
    company: "Société",
    privatePerson: "Particulier",
    complicated: "client difficile",
    complicatedClient: "Client difficile",
    companyName: "Raison sociale",
    fullName: "Nom complet",
    firstName: "Prénom",
    lastName: "Nom",
    phone: "Téléphone",
    emailAddress: "Adresse e-mail",
    emailAddresses: "Adresses e-mail",
    someEmailAddresses: "Adresse(s) e-mail",
    useMultipleEmails: "Utiliser plusieurs adresses",
    turnOffMultipleEmails: "Revenir à une seule adresse",
    primary: "Principale",
    registryCode: "Numéro RC",
    personalCode: "CIN",
    address: "Adresse",
    about: "À propos",
    added: "Ajouté le",
  },
  vehicles: {
    findVehicles: "Rechercher un véhicule",
    searchPlaceholder: "VIN, immatriculation, propriétaire ou marque…",
    information: "Informations véhicule",
    newVehicle: "Nouveau véhicule",
    producer: "Marque",
    producerPlaceholder: "Saisir la marque",
    model: "Modèle",
    makeAndModel: "Marque et modèle",
    regNr: "Immatriculation",
    registrationNr: "Immatriculation",
    vin: "VIN",
    vinCode: "Code VIN",
    odometer: "Kilométrage",
    owner: "Propriétaire",
    noOwner: "Aucun propriétaire",
    about: "À propos",
  },
  inventory: {
    findInventory: "Rechercher une pièce",
    searchPlaceholder: "code ou libellé…",
    information: "Informations pièce détachée",
    newSparePart: "Nouvelle pièce détachée",
    productCode: "Référence",
    productName: "Désignation",
    price: "Prix",
    quantity: "Quantité",
    discount: "Remise",
    location: "Emplacement",
    about: "À propos",
    addLocation: "Ajouter un emplacement",
    newLocationPlaceholder: "Nom du nouvel emplacement",
  },
  settings: {
    companyInformation: "Informations de la société",
    name: "Nom",
    phone: "Téléphone",
    address: "Adresse",
    email: "E-mail",
    bankAccount: "Compte bancaire",
    regNr: "Numéro RC",
    taxId: "Identifiant fiscal",
    invoiceOptions: "Options de facturation",
    offerOptions: "Options de devis",
    vatRate: "Taux de TVA",
    surcharge: "Pénalité de retard",
    disclaimer: "Mentions légales",
    signatureLine: "Ligne de signature",
    emailContent: "Contenu de l’e-mail",
  },
  profile: {
    myInformation: "Mes informations",
    personalInformation: "Informations personnelles",
    fullName: "Nom complet",
    firstName: "Prénom",
    lastName: "Nom",
    userName: "Identifiant",
    email: "E-mail",
    changePassword: "Changer le mot de passe",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    deleteAccount: "Supprimer le compte",
    deleteAccountWarning:
      "Vous ne souhaitez plus utiliser le service ? Vous pouvez supprimer votre compte ici. Cette action est irréversible : toutes les informations liées à ce compte seront définitivement effacées.",
    confirmDeleteAccount: "Oui, supprimer mon compte",
  },
  auth: {
    signInTitle: "Connectez-vous à votre compte",
    username: "Identifiant",
    password: "Mot de passe",
    rememberMe: "Se souvenir de moi",
    forgotPassword: "Mot de passe oublié ?",
    signIn: "Se connecter",
    orContinueWith: "Ou continuer avec",
  },
  address: {
    country: "Pays",
    street: "Adresse",
    city: "Ville",
    region: "Région",
    postalCode: "Code postal",
  },
  badges: {
    issued: "Émis",
    accepted: "Accepté",
    paid: "Payée",
    unpaid: "Impayée",
    overdue: "En retard",
  },
  work: {
    client: "Client",
    vehicle: "Véhicule",
    invoice: "Facture",
    number: "Intervention",
    startedOn: "Ouverte le",
    completedOn: "Terminée le",
    mechanics: "Mécaniciens",
    activities: "Réparation, devis",
    workNumber: "Intervention n°",
    information: "Informations intervention",
    newWork: "Nouvelle intervention",
    repairJob: "Réparation",
    manyOffers: "Plusieurs devis",
    estimateShort: "Devis",
    invoiceShort: "Facture",
    downloadEstimate: "Télécharger le devis",
    downloadInvoice: "Télécharger la facture",
    isInProgress: "En cours",
    findWork: "Rechercher une intervention",
    searchPlaceholder: "numéro, client, VIN ou immatriculation",
    productOrService: "Pièce ou prestation",
    productPlaceholder: "code ou libellé…",
    noProducts: "Aucune pièce ni prestation pour l’instant",
    startWith: "Commencer par",
    odometerPlaceholder: "Kilométrage",
    about: "À propos",
    addMechanic: "Ajouter un mécanicien",
    newMechanic: "Nouveau",
    selectMechanic: "Choisir un mécanicien",
    // The two switches beside the client and vehicle pickers on the edit form.
    clientUndisclosed: "Client non communiqué",
    allVehicles: "Tous les véhicules",
    deleteMechanic: "Supprimer le mécanicien",
    removeTitle: "Suppression de",
    removeMechanicConfirm: "Êtes-vous sûr de vouloir supprimer ce mécanicien ? Assurez-vous qu’il n’est affecté à aucune intervention, sinon la suppression échouera.",
    newMechanicPlaceholder: "Nom du nouveau mécanicien",
    // Actions on the intervention record. The verbs name the business act, not the HTTP verb.
    makeAnOffer: "Créer un devis",
    startRepairJob: "Démarrer la réparation",
    createACopy: "Créer une copie",
    issueInvoice: "Émettre la facture",
    deleteInvoice: "Supprimer la facture",
    sendInvoice: "Envoyer la facture",
    resendInvoice: "Renvoyer la facture",
    paymentReceived: "Paiement reçu",
    markUnpaid: "Marquer comme impayée",
    closeWork: "Fermer l’intervention",
    reopenWork: "Rouvrir l’intervention",
    deleteWork: "Supprimer l’intervention",
    deleteWorkConfirm: "Êtes-vous sûr de vouloir supprimer cette intervention ?",
    deleteActivityConfirm: "Êtes-vous sûr de vouloir supprimer cet élément ?",
    issueOffer: "Émettre le devis",
    reissueOffer: "Réémettre le devis",
    sendOffer: "Envoyer le devis",
    resendOffer: "Renvoyer le devis",
    clientAccepted: "Devis accepté par le client",
    addRow: "Ajouter une ligne",
    reorderRow: "Réordonner la ligne",
    removeRow: "Retirer la ligne",
    notesPlaceholder: "Ajouter des notes…",
    addRows: "Ajouter cinq lignes",
    applyDiscount: "Appliquer une remise",
    startEntry: "Commencer la saisie",
    // Section titles on the record.
    identity: "Identité",
    timeline: "Activités",
    openedOn: "Ouverte le",
    invoicing: "Facturation",
    payment: "Paiement",
    selectActivity: "Sélectionner une activité",
    workActions: "Actions sur l’intervention",
    paid: "Payée",
    unpaid: "Impayée",
    dueIn: "Délai de paiement",
    days: "jours",
    issuedOnBy: "Émise le",
    notIssued: "Non émis",
    invoiceFrom: "Facture du",
    invoiceTo: "Facture au",
    workFrom: "Intervention du",
    workTo: "Intervention au",
  },
} as const;
