export const serviceHistoryLabels = {
  clientTitle: "Historique des interventions",
  vehicleTitle: "Historique d’entretien",
  clientEmpty: "Aucune intervention enregistrée pour ce client.",
  vehicleEmpty: "Aucun historique d’entretien pour ce véhicule.",
  error: "Impossible de charger l’historique pour le moment.",
  interventionCount: "Interventions",
  invoicedTotal: "Total facturé",
  lastService: "Dernière intervention",
  lastOdometer: "Dernier kilométrage enregistré",
  date: "Date",
  openedOn: "Ouverte",
  closedOn: "Clôturée",
  work: "Intervention",
  vehicle: "Véhicule",
  client: "Client",
  odometer: "Kilométrage",
  status: "Statut",
  summary: "Prestations",
  parts: "Pièces",
  amount: "Montant",
  invoice: "Facture",
  actions: "Actions",
  notInvoiced: "Non facturée",
  viewWork: "Voir l’intervention",
  viewInvoice: "Voir la facture",
  downloadInvoice: "Télécharger le PDF",
  previous: "Précédent",
  next: "Suivant",
  statuses: {
    completed: "Facturée",
    closed: "Clôturée",
    inprogress: "En cours",
    default: "Ouverte",
  } as Record<string, string>,
};
